### ISSUE TITLE
Markbot image naming issue

### ISSUE THREAD

**Issue by prim0062** [prim0062/production-prepping-compression#1]
This is the project with the issue I showed you in class this Wednesday.

I'm currently having an issue with Markbot. I've completed the exercise Production prepping & compression, but Markbot keeps suggesting the image files are missing, and can only be found if I rename them to their original, unconventional names.
@charlie-quinn

**Comment by charlie-quinn** [comment]
- [x] move your local assignment folder to your Desktop
- [x] delete your repository on GitHub and refork + clone this assignment from the original assignment's link
- [x] add your old files from your desktop to the new assignment folder

This should fix the issue, I'm not getting any other error other than `MarkbotFile not found`.

**Comment by prim0062** [comment]
My apologies, the markbot files didn't upload properly when I uploaded the project. I've re-added all the original files including the markbot ones. Please redownload the project to view my initial issue.
@charlie-quinn

**Comment by charlie-quinn** [comment]
- [x] replace your current `assets` with the originals (this check ran correctly on my end)

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by prim0062** [comment]
Replacing the assets with the original files gives me this response
![d63abd955c11223ab033cc15fea7bd16](https://user-images.githubusercontent.com/43246445/70383081-bb9fe200-1935-11ea-9e69-0b4af9762002.png)

**Comment by charlie-quinn** [comment]
What version of Markbot are you running @prim0062 ?

**Comment by charlie-quinn** [comment]
I'm running version `8.2.2` and am able to hand in the project using your files. 🤔

**Comment by prim0062** [comment]
I am also running version 8.2.2. I'm thinking the issue has to do with me using a Windows since it works on your Mac, and not either of my PCs.

**Comment by charlie-quinn** [comment]
Alright, I'll manually add this grade in for you. 🤖✅

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
